adapt build for sonar and prepare deployment

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -1,130 +1,298 @@
 name: Maven Build
+run-name: >
+  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }} 
 
 on:
-  push:
-    branches:
-      - main
-      - feature/**
   workflow_dispatch:
+    inputs:
+      deploy:
+        description: "By default feature branches are not deployed. Enable to enforce"
+        required: true
+        type: boolean
+        default: false
+  push:
+    branches: [ "main", "master", "feature/**", "release/**" ]
+  schedule:
+    - cron: 5 5 * * MON-FRI # daily at 5:05 am (Except on Weekends)
 
 jobs:
+
   setup:
+
+    permissions:
+      contents: read
+      packages: write
+
     name: Setup
+
     runs-on: ubuntu-latest
+
     outputs:
       BRANCH_MAVEN_VERSION: ${{ steps.set_version.outputs.BRANCH_MAVEN_VERSION }}
-      GIT_BRANCH: ${{ steps.set_version.outputs.GIT_BRANCH }}
+      BRANCH_NAME: ${{ steps.set_version.outputs.GIT_BRANCH }}
+      MVN_VERSION: ${{ steps.set_version.outputs.MVN_VERSION }}
+
     steps:
       - name: Checkout project
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
       - name: Set up java 17
         uses: actions/setup-java@v4
         with:
           java-version: 17
           distribution: 'temurin'
           cache: 'maven'
+
       - name: Cache maven packages
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
+
       - name: Set Maven Versions
         id: set_version
         run: './.github/scripts/set_maven_version.sh'
-  analyze:
-    name: Build and Analyze
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout project
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Set up java 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: 'temurin'
-          cache: 'maven'
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache maven packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Setup maven settings.xml
-        uses: s4u/maven-settings-action@v3.0.0
-        with:
-          servers: >
-            [
-              {
-                "id": "central",
-                "username": "${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}",
-                "password": "${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}"
-              },
-              {
-                "id": "snapshots",
-                "username": "${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}",
-                "password": "${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}"
-              }
-            ]
-      - name: Build and Analyze
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ch.swissperform:template-java-maven
+
   build:
-    name: Build
     runs-on: ubuntu-latest
+
     needs: [ setup ]
+
+    permissions:
+      contents: read
+      packages: write
+
     steps:
-      - name: Checkout project
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Set up java 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: 'temurin'
-          cache: 'maven'
-      - name: Cache maven packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Setup maven settings.xml
-        uses: s4u/maven-settings-action@v3.0.0
+      - uses: actions/checkout@v4
+
+      - name: Setup Maven settings.xml
+        uses: whelk-io/maven-settings-xml-action@v21
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
         with:
           servers: >
             [
               {
                 "id": "central",
-                "username": "${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}",
-                "password": "${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}"
+                "username": "${ARTIFACTORY_USERNAME}",
+                "password": "${env.ARTIFACTORY_TOKEN}"
               },
               {
                 "id": "snapshots",
-                "username": "${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}",
-                "password": "${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}"
+                "username": "${ARTIFACTORY_USERNAME}",
+                "password": "${env.ARTIFACTORY_TOKEN}"
+              },
+              {
+                "id": "github",
+                "username": "${env.GITHUB_ACTOR}",
+                "password": "${env.GITHUB_TOKEN}"
               }
             ]
-      - name: Build
+          output_file: ${{ github.workspace }}/.github/.m2/artifactory/settings.xml # by default it goes to ~/.m2/settings.xml
+
+      - name: Run Maven Build
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
+          ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}
+          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}
+          FORCE_DEPLOY: ${{ github.event.inputs.deploy }}
         run: |
-          BRANCH=$(git rev-parse --abbrev-ref HEAD)
-          if [[ $BRANCH == "main" ]];
-          then
-            echo "Releasing main branch, resuming"
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+          if [[ "${BRANCH_NAME}" == "main" ]]; then
+            echo "::notice:: ### Build of Main. Version: $BRANCH_MVN_VERSION"
           else
-            mvn -B versions:set -DnewVersion="${{ needs.setup.outputs.BRANCH_MAVEN_VERSION }}"
+            echo "::notice:: ### Build of Feature Branch ${BRANCH_NAME}. Version: $BRANCH_MVN_VERSION"
+            mvn -B versions:set -Partifactory -e -DnewVersion="$BRANCH_MVN_VERSION" -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml
           fi
-          mvn -B deploy
+          if [[ "${BRANCH_NAME}" == "main" ]] || [[ "${FORCE_DEPLOY}" == "true" ]]; then
+            mvn -B deploy -Partifactory -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml
+          else
+            mvn -B install -Partifactory -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml
+          fi
+
+  deploy:
+    runs-on: [ camunda-ci ]
+
+    needs: [ setup,build ]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Maven settings.xml
+        uses: whelk-io/maven-settings-xml-action@v21
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
+        with:
+          servers: >
+            [
+              {
+                "id": "central",
+                "username": "${ARTIFACTORY_USERNAME}",
+                "password": "${env.ARTIFACTORY_TOKEN}"
+              },
+              {
+                "id": "snapshots",
+                "username": "${ARTIFACTORY_USERNAME}",
+                "password": "${env.ARTIFACTORY_TOKEN}"
+              },
+              {
+                "id": "github",
+                "username": "${env.GITHUB_ACTOR}",
+                "password": "${env.GITHUB_TOKEN}"
+              }
+            ]
+          output_file: ${{ github.workspace }}/.github/.m2/artifactory/settings.xml # by default it goes to ~/.m2/settings.xml
+
+      - name: Deploy
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
+          ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}
+          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          MVN_VERSION: ${{needs.setup.outputs.MVN_VERSION}}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          FORCE_DEPLOY: ${{ github.event.inputs.deploy }}
+          TOMCAT_NAME: tomcat
+          TOMCAT_DIR: /opt/tomcat/updated
+          DB_SECRET: ${{ secrets.CI_JTT_DB_PASSWORD }}
+          ENVIRONMENT: ci
+          TOMCAT_USER: tomcat
+        run: |
+          # run deploy script
+          "${GITHUB_WORKSPACE}/.github/workflows/scripts/deploy.sh"
+
+  sonar-scan:
+
+    needs: [ setup,build ]
+
+    permissions:
+      actions: read
+      contents: write
+
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - uses: actions/checkout@v4
+
+      - name: Set up JDK 8
+        uses: actions/setup-java@v4
+        with:
+          java-version: 8
+          distribution: 'temurin'
+          cache: 'maven'
+          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
+          settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+      - name: Setup Maven settings.xml
+        uses: whelk-io/maven-settings-xml-action@v21
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
+          ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}
+          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}
+        with:
+          servers: >
+            [
+              {
+                "id": "central",
+                "username": "${ARTIFACTORY_USERNAME}",
+                "password": "${env.ARTIFACTORY_TOKEN}"
+              },
+              {
+                "id": "snapshots",
+                "username": "${ARTIFACTORY_USERNAME}",
+                "password": "${env.ARTIFACTORY_TOKEN}"
+              },
+              {
+                "id": "github",
+                "username": "${env.GITHUB_ACTOR}",
+                "password": "${env.GITHUB_TOKEN}"
+              }
+            ]
+          output_file: ${{ github.workspace }}/.github/.m2/artifactory/settings.xml
+
+      - name: Run with Jacoco
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
+          ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}
+          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+          
+          if [[ "${BRANCH_NAME}" == "main" ]]; then
+            echo "::notice:: ### Build of Main. Version: $BRANCH_MVN_VERSION"
+          else
+            echo "::notice:: ### Build of Feature Branch ${BRANCH_NAME}. Version: $BRANCH_MVN_VERSION"
+            mvn -B versions:set -Partifactory -e -DnewVersion="$BRANCH_MVN_VERSION" -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml
+          fi
+          mvn -B clean verify \
+          -P 'artifactory,coverage' \
+          -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml \
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: 17
+          distribution: 'temurin'
+          cache: 'maven'
+          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
+          settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+      - name: sonar
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_CI_SWP_URL }}
+          ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_CI_SWP_USERNAME }}
+          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_CI_SWP_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          if [[ "${BRANCH_NAME}" == "main" ]]; then
+            echo "::notice:: ### Build of Main. Version: $BRANCH_MVN_VERSION"
+            mvn -B sonar:sonar \
+                -P 'artifactory,coverage' \
+                -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml \
+                -Dsonar.token=${SONAR_TOKEN} \
+                -Dsonar.host.url=https://sonarcloud.io \
+                -Dsonar.sourceEncoding=UTF-8 \
+                -Dsonar.organization=swissperform \
+                -Dsonar.projectKey=ch.swp.dex.auslandtausch \
+                -Dsonar.branch.name=main
+          else
+            echo "::notice:: ### Build of Feature Branch ${BRANCH_NAME}. Version: $BRANCH_MVN_VERSION"
+            mvn -B versions:set -Partifactory -e -DnewVersion="$BRANCH_MVN_VERSION" -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml
+            mvn -B sonar:sonar \
+                -P 'artifactory,coverage' \
+                -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml \
+                -Dsonar.token=${SONAR_TOKEN} \
+                -Dsonar.host.url=https://sonarcloud.io \
+                -Dsonar.sourceEncoding=UTF-8 \
+                -Dsonar.organization=swissperform \
+                -Dsonar.projectKey=ch.swp.dex.auslandtausch \
+                -Dsonar.branch.name=${BRANCH_NAME} \
+                -Dsonar.branch.target=main
+          fi
+          echo "https://sonarcloud.io/summary/overall?id=ch.swp.dex.auslandtausch" >> $GITHUB_STEP_SUMMARY
